version: '3'

services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_HOST: db
  #     DATABASE_PORT: 5432
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: 230403
  #     DATABASE_NAME: schooldb
  #   depends_on:
  #     - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3001:3000'
  #   depends_on:
  #     - backend

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 230403
      POSTGRES_DB: schooldb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
